//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyonnBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.client_shop = new HashSet<client_shop>();
        }
    
        public int client_id { get; set; }
        public Nullable<byte> client_status_id { get; set; }
        public string client_name { get; set; }
        public string client_mobile { get; set; }
        public string client_location { get; set; }
        public Nullable<System.DateTime> client_registration_date { get; set; }
    
        public virtual client_status client_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_shop> client_shop { get; set; }
    }
}
