//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyonnBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public long order_details_id { get; set; }
        public Nullable<long> order_id { get; set; }
        public Nullable<int> product_details_id { get; set; }
        public Nullable<byte> order_quantity { get; set; }
        public Nullable<decimal> order_price { get; set; }
    
        public virtual order order { get; set; }
        public virtual products_details products_details { get; set; }
    }
}
