//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyonnBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public long order_id { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<decimal> total_orders_price { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.TimeSpan> order_time { get; set; }
        public Nullable<System.DateTime> order_delivery_date { get; set; }
        public Nullable<System.TimeSpan> order_delivery_time { get; set; }
        public int Orders_StatusID { get; set; }
    
        public virtual client_shop client_shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual Orders_Status Orders_Status { get; set; }
    }
}
