//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyonnBL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oyonnEntities : DbContext
    {
        public oyonnEntities()
            : base("name=oyonnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<client_shop> client_shop { get; set; }
        public virtual DbSet<client_status> client_status { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<Orders_Status> Orders_Status { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<products_details> products_details { get; set; }
    }
}
