//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyonnBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products_details()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int product_details_id { get; set; }
        public Nullable<short> product_id { get; set; }
        public string product_name_ar { get; set; }
        public string product_name_en { get; set; }
        public string product_img { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<decimal> product_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual product product { get; set; }
    }
}
